### ISSUE TITLE
When loading a gun with a stack of bullets it consumes the whole stack and only gets 1 clip

### ISSUE THREAD

**Issue by lag42** [TeamWizardry/Shotguns-And-Glitter#2]
Hold a stack of bullets in your off hand and then right click with a gun in your main hand and you'll see what I'm talking about

**Comment by Demoniaque** [comment]
@yrsegal you redid the ammo system so this is on you.

**Comment by yrsegal** [comment]
yep, def on me

**Comment by yrsegal** [comment]
https://github.com/TeamWizardry/Shotguns-And-Glitter/commit/d48cee61b1857f5f026393b046436f2abd69234a
