### ISSUE TITLE
I fucking love loud as fuck sounds

### ISSUE THREAD

**Issue by Fortist** [TeamWizardry/Shotguns-And-Glitter#3]
Even at 50% Overall sound levels, they are ear shattering.
And I noticed in the sounds.json they're not tied to any sound option, so theres that.

Plus the music is obnoxious, maybe a jingle would be better. I dont really care I wouldnt use them.

**Comment by Demoniaque** [comment]
I fucking love loud as fuck sounds too! We should go out some time.

I'll be implementing a proper sound system in the next update. dont you worry
