### ISSUE TITLE
Bugs: Loads of bugs

### ISSUE THREAD

**Issue by Akitori** [TeamWizardry/Shotguns-And-Glitter#5]
I think some bugs have been reported, but imma put this video here regardless with a list of bugs in text.

https://youtu.be/8S_6v99YuIY

1. Guns consume entire stack, reported elsewhere i believe.
2. Magazines/drums are not craftable
3. shotgun does piss poor damage (10 shots to kill a villager at point blank)
4. Bullets sometimes hit the shooter.
5. Flashbang affects even when i am staring at a wall
6. Why do shotguns only have one slot? At least 2 rounds would be cool imo, but idk.

**Comment by Akitori** [comment]
Update: With the newest version, these bugs happen.

https://youtu.be/zNuiTp4ryNE

In short: can't load minigun, pistol, or shotgun with respective bullet types. 
Sniper can be loaded with all types of rounds.
miniguns and pistols can use magazines/drums, WHICH ARE STILL NOT CRAFTABLE
shotguns flat out don't load.

**Comment by Demoniaque** [comment]
- In short: can't load minigun, pistol, or shotgun with respective bullet types.
 intended

- Sniper can be loaded with all types of rounds.
 @yrsegal 

- miniguns and pistols can use magazines/drums, WHICH ARE STILL NOT CRAFTABLE
 @yrsegal 

- shotguns flat out don't load
@yrsegal

**Comment by yrsegal** [comment]
Magazines and drums are craftable

Sniper... how did I mess it up that badly (same with shotgun)

**Comment by Demoniaque** [comment]
I definitely buffed the shotgun very slightly this update. might need a bigger buff but im not sure. needs more testing
