### ISSUE TITLE
Invisible shotgun and rifle

### ISSUE THREAD

**Issue by Javin7** [TeamWizardry/Shotguns-And-Glitter#6]
Hello,
I'm using the latest version of Shotguns & Glitter and the shotgun and the rifle have invisible textures.
Thank you for making this amazing mod!

**Comment by Demoniaque** [comment]
Take a screenshot

**Comment by Javin7** [comment]
https://i.imgur.com/SM7j1Qx.png

**Comment by yrsegal** [comment]
could you upload your atlas sheet? It should be in your minecraft instance folder.

**Comment by Javin7** [comment]
Can't seem to find it anywhere.

**Comment by yrsegal** [comment]
it's called `textures_0.png`

**Comment by Javin7** [comment]
Only thing that pops up is this, and there's nothing of the sort inside the log.
https://i.imgur.com/GWox7qG.png

**Comment by yrsegal** [comment]
it should be in the same folder where `mods` is.

**Comment by Javin7** [comment]
https://i.imgur.com/SoADNsk.png

**Comment by Javin7** [comment]
Issue was caused by FoamFix Anarchy 0.9.6, closing.
