### ISSUE TITLE
Sentry/Turret doesnt seem to work.

### ISSUE THREAD

**Issue by Zunlite** [TeamWizardry/Shotguns-And-Glitter#8]
So I finally got the resources to craft a turret/sentry, I inserted coal with a hopper, powered it via redstone, got an enemy in front of it, and.... nothing??

**Comment by Zunlite** [comment]
![2018-07-10_11 47 22](https://user-images.githubusercontent.com/40839781/42521524-1b3636aa-8437-11e8-83e1-55a3af5d5eeb.png)

**Comment by Demoniaque** [comment]
You didn't add any small bullets.
