### ISSUE TITLE
Assorted issues

### ISSUE THREAD

**Issue by LemADEC** [TeamWizardry/Shotguns-And-Glitter#9]
As of version 1.5, multiple issues are observed:
1- curseforge page says to reload turrets with small bullets, book says to use magical bullets, practically we can only use "Rounds".
2- in the manual, only the getting started icon changes when hovering it.
3- the manual sometime appears transparent (no background, no text, just the search glass).
4- turret fails to reach target more than 8 blocks away.
5- turret attacks passive mobs.
6- turret consumes 1 fuel item and 1 bullet per shot, whether it's sticks or coal. This is inconsistent and too expensive for both fuel and ammunition.
7- discord link and video on curse page are invalids.
8- book doesn't explain how to reload your guns (i.e. we need to place ammunition in the off hand slot).
9- Magazine and drums are missing in the creative tab.

**Comment by Demoniaque** [comment]
Thanks for the report

2 is a liblib issue.
5 is intended but should be changed i suppose

@yrsegal can you deal with the rest pls?
Ill fix the curseforge page up. We also need to correct the drum recipe

**Comment by SwissCheese5** [comment]
Fixed 99% of these
